### ISSUE TITLE
这个堆叠的顺序如何更改

### ISSUE THREAD

**Issue by protectedMan** [hnsycsxhzcsh/DiscussionAvatarView#1]
![image](https://user-images.githubusercontent.com/17565737/61990759-3a783a80-b079-11e9-8acc-36cddc1e382d.png)

我这边需求是前压后

**Comment by wangfufu** [comment]
同问

**Comment by protectedMan** [comment]
一个hacker的方式用elevation实现，很简单
![image](https://user-images.githubusercontent.com/17565737/63261614-7c7e5000-c2b6-11e9-9d53-327979a90616.png)
